In [1]:
# pading 是对input_data 
import torch

In [3]:
input_data = [1,2,3,4,5,
              2,4,1,2,3,
              4,1,2,3,5,
              6,7,1,2,4,
              9,2,8,5,6]

In [8]:
input_data = torch.Tensor(input_data).view(1,1,5,5)
conv_layer = torch.nn.Conv2d(1,1,kernel_size=(3,3),padding=1,bias=False)
kernel_data = torch.Tensor([1,2,3,4,5,6,7,8,9]).view(1,1,3,3)
conv_layer.weight.data = kernel_data

In [10]:
output = conv_layer(input_data)
output

tensor([[[[ 69.,  87., 101., 112.,  79.],
          [ 83., 102., 103., 141.,  98.],
          [153., 153., 119., 126.,  91.],
          [173., 228., 182., 211., 124.],
          [ 90., 117.,  93., 110.,  60.]]]],
       grad_fn=<MkldnnConvolutionBackward>)

In [11]:
# strip 增加步长
input_data = torch.Tensor(input_data).view(1,1,5,5)
conv_layer = torch.nn.Conv2d(1,1,kernel_size=(3,3),stride=2,bias=False)
kernel_data = torch.Tensor([1,2,3,4,5,6,7,8,9]).view(1,1,3,3)
conv_layer.weight.data = kernel_data

In [13]:
output = conv_layer(input_data)
output

tensor([[[[102., 141.],
          [228., 211.]]]], grad_fn=<MkldnnConvolutionBackward>)

In [14]:
# maxpolling
input_data = [3,3,1,4,
              2,8,6,2,
              2,4,9,3,
              5,4,2,1]

In [16]:
# maxpooling 将图像分割成几部分，每个点取其中最大的。
input_data = torch.Tensor(input_data).view(1,1,4,4)
conv_layer = torch.nn.MaxPool2d(kernel_size=(2,2))
output = conv_layer(input_data)
output

tensor([[[[8., 6.],
          [5., 9.]]]])