In [1]:
import torch

In [24]:
batch_size = 1
# 一个句子由多个词组成，这个句子有多长
seq_len = 4
# 每个单词转成向量有多少维度的特征值
input_size = 7
hidden_size = 2

In [28]:
data = torch.randn(batch_size,seq_len,input_size)
hidden = torch.zeros(1,batch_size,hidden_size)
print(data)
print(hidden)

tensor([[[-5.4768e-01, -1.4844e-01, -4.2723e-01, -4.7524e-01, -1.3424e-01,
          -1.0599e-01, -1.6275e-04],
         [ 5.3523e-01, -3.7972e-01, -1.0529e+00,  9.4737e-01,  4.1260e-01,
           4.8436e-01,  1.4154e+00],
         [ 2.8794e-01,  1.7778e+00,  1.0265e+00, -2.9763e-01,  3.6110e-01,
          -1.4797e+00,  6.0531e-02],
         [ 4.9569e-02,  1.3606e+00, -2.8700e-02,  1.6045e+00,  1.1292e+00,
          -8.7423e-01,  7.3359e-01]]])
tensor([[[0., 0.]]])


In [ ]:
# 主要是计算好 输入 data 的数据大小 和 hidden的数据大小，其参数不需要考虑，pytorch会自动算。
# 使用RNNCELL
rnn_cell = torch.nn.RNNCell(input_size=input_size , hidden_size= hidden_size)

In [29]:
# 这个RNN由两个全连接层组成，对应的两个hidden_state的维度是2，输入向量维度是1
n_layers = 1
rnn = torch.nn.RNN(input_size, hidden_size, n_layers, batch_first=True)
output,hn = rnn(data,hidden)
print(output)
print(hn)

tensor([[[-0.2305, -0.8148],
         [-0.3367, -0.9558],
         [ 0.8655, -0.8519],
         [ 0.1813,  0.4746]]], grad_fn=<TransposeBackward1>)
tensor([[[0.1813, 0.4746]]], grad_fn=<StackBackward>)


In [27]:
for i , v in enumerate(data):
    print("input_size:",v.shape)
    h = rnn_cell(v,hidden)
    print("hidden_size:",h.shape)
    print(h)

input_size: torch.Size([1, 6])
hidden_size: torch.Size([1, 2])
tensor([[-0.1442, -0.6908]], grad_fn=<TanhBackward>)
input_size: torch.Size([1, 6])
hidden_size: torch.Size([1, 2])
tensor([[0.8520, 0.9372]], grad_fn=<TanhBackward>)
input_size: torch.Size([1, 6])
hidden_size: torch.Size([1, 2])
tensor([[-0.2674,  0.5985]], grad_fn=<TanhBackward>)


In [ ]:
#rnn 有两个 w, 一个是 w_ih  另一个是 w_hh