In [2]:
import torch

In [15]:
batch_size = 1
seq_len = 3
input_size = 6
hidden_size = 2

In [28]:
data = torch.randn(seq_len,batch_size,input_size)
hidden = torch.zeros(batch_size,hidden_size)
data

tensor([[[ 0.3097,  0.0361,  0.9337, -0.3325, -1.1094, -0.4357]],

        [[ 0.4168, -1.6464,  0.7457,  0.4940, -2.0401, -1.3703]],

        [[ 0.5571, -1.1191,  2.1128, -0.0872,  0.8190,  0.4667]]])

In [17]:
# 主要是计算好 输入 data 的数据大小 和 hidden的数据大小，其参数不需要考虑，pytorch会自动算。
# 使用RNNCELL
cell = torch.nn.RNNCell(input_size=input_size , hidden_size= hidden_size)

In [27]:
for i , v in enumerate(data):
    print("input_size:",v.shape)
    h = cell(v,hidden)
    print("hidden_size:",h.shape)
    print(h)

input_size: torch.Size([1, 6])
hidden_size: torch.Size([1, 2])
tensor([[-0.1442, -0.6908]], grad_fn=<TanhBackward>)
input_size: torch.Size([1, 6])
hidden_size: torch.Size([1, 2])
tensor([[0.8520, 0.9372]], grad_fn=<TanhBackward>)
input_size: torch.Size([1, 6])
hidden_size: torch.Size([1, 2])
tensor([[-0.2674,  0.5985]], grad_fn=<TanhBackward>)


In [ ]:
#rnn 有两个 w, 一个是 w_ih  另一个是 w_hh